### ISSUE TITLE
WooThemes Helper conflict with Homepage Control

### ISSUE THREAD

**Issue by stuartduff** [woothemes/homepage-control#17] opened 2015-05-11 14:26 UTC
When v2.0.0 of Homepage Control is installed and WooThemes Helper is activated it stops homepage control from functioning not being able to drag and drop reorder or enable  / disable check-boxes.

I have tested one Storefront so far but from customer reports other theme products seem to be affected too like Hub etc.

**Comment by stuartduff** [comment] 2015-05-14 10:32
@tiagonoronha can you prioritize this issue man and try to push an  update out ASAP as it's causing. continued support ;)

Cheers dude

**Comment by danieldudzic** [comment] 2015-05-14 18:22
https://github.com/woothemes/woothemes-updater/issues/77 - related?

**Comment by tiagonoronha** [comment] 2015-05-14 18:38
Will fix in the morning.

**Comment by tiagonoronha** [comment] 2015-05-15 18:53
@stuartduff tried with a bunch of different products and WooThemes helper installed, works every time. :/

Is there anything specific I have to do for HC to stop working?

**Comment by danieldudzic** [comment] 2015-05-15 22:03
@tiagonoronha Did you try adding a license to the product?

**Comment by tiagonoronha** [comment] 2015-05-15 22:09
@danieldudzic yes!

**Comment by danieldudzic** [comment] 2015-05-15 22:26
> I found the bug in the storefront code. On line 51 in the inc/structure/hooks.php the add_action function "storefront_homepage_content" is set to 10 and causes a conflict with the Parallax slider because the action is also set to 10. I simply swapped the number out with 20 and the homepage control plugin started working for me.

Perhaps that will help?

**Comment by tiagonoronha** [comment] 2015-05-15 22:29
@danieldudzic whoa! thanks, I'll test that combination.

**Comment by tiagonoronha** [comment] 2015-05-15 22:55
@danieldudzic just tested with Parallax Hero, no luck, all is good. 

I don't have a license for the extension though, I'll test with one again asap.

**Comment by TinyGiantStudios** [comment] 2015-05-22 13:25
Any feedback on this?

**Comment by tiagonoronha** [comment] 2015-05-22 15:39
@stuartduff @TinyGiantStudios I think I found the issue, but it's being caused by the helper plugin.

**Comment by stuartduff** [comment] 2015-05-22 15:41
@tiagonoronha I'm still getting two different results on both of my test sites, can you recreate it now?

**Comment by tiagonoronha** [comment] 2015-05-22 15:42
@stuartduff nope, but I see a JS error in the console, also reported here by Matty: https://github.com/woothemes/woothemes-updater/issues/78

**Comment by tiagonoronha** [comment] 2015-05-22 15:42
Saw that in one of the customer tickets you sent

**Comment by tiagonoronha** [comment] 2015-06-18 13:08
As I said above, this issue is not related to Homepage Control. Please follow up here: woothemes/woothemes-updater#78

Closing!

**Closed by tiagonoronha** 2015-06-18 13:08 UTC
Labels: bug
